apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-server
  namespace:  argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jaimejorge/backtest
    targetRevision: HEAD
    path: k8s/app/echo-server
  destination:
    server: https://rudder.mpi-internal.com
    namespace: cre-dev
  syncPolicy:
    automated:
      # Specifies if resources should be pruned during auto-syncing ( false by default ).
      prune: true
      # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster
      # and no git change detected ( false by default ).
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /metadata/annotations
  - kind: Service
    jsonPointers:
    - /metadata/annotations
  - group: extensions
    kind: Ingress
    jsonPointers:
    - /metadata/annotations
