apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - image: dockerhub.containers.mpi-internal.com/tomcat:8.0-alpine
        name: echoserver
        # SCHIP clusters have deny-notbesteffort quota setting prevents you setting resources
        # resources:
        #   requests:
        #     memory: 32Mi
        #     cpu: 100m
        #   limits:
        #     memory: 64Mi
        #     cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: echo-server
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo-server
  annotations:
    kubernetes.io/ingress.class: "heimdall"
spec:
  rules:
  - host: echo-server.cre-dev.schip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: echo-server
          servicePort: 80
